working_list = ["You work at mcdonalds for 8 hours and earn", "You was fixing roofs and earned", "You started working as a Minecraft youtuber and earned", "You started working as a discord moderator and earned", "You started working as a python developer and earned", "You fixed a major bug in the 24/7 Casino Bot and earned", "You fought for the UFC and knocked out Mike Tyson and earned", "You worked at pizza hut from 8am to 4pm and earned", "You won a Fortnite tournament and won", "You worked at a gas station for 8 hours and earned", "You serve in the Soviet union and earned", "You work as a maid for the Nazi and earned", "You work at wendys overnight and earned", "You mopped the floor for your chores and got", "You help your team group project by a lot and earned", "You work for popeye and earned", "You worked at the car wash and earned",
                "You worked on developing Mechanical Keyboards and earned", "You do your house chores and earned", "You help your school organization and earned", "You work as a church janitor and got paid", "You work for the handsome beard man and he gave You a tip of", "You work as a producer in the show Kitchen Nightmares and You earned", "You worked as Billy Bob assistant and he gave You a fine tip of", "You worked overnight at Walmart for one hour and earned", "You share your design it which goes well and You earned", "You built a spaceship for NASA and earned", "You leaked Hillary Clinton’s emails and earned", "You work in the animal shelter and earned", "You clean the garden and earned", "You work as a janitor and earned", "You work as blackpink producer and earned", "You work as BTS producer and earned", "You help your grandma to cook and earned"]

crime_list = ["You stole from mcdonalds and resold the stolen goodies on the black market and earned", "You stole Pablo Esobar drug stash and sold it for", "You beatup the school bully and got paid", "You hacked into the goverment and stole", "You done a bank heist and stole", "You robbed Bill Gates and stole", "You stole a computer from school and sold it and made", "You hacked into Wikipedia and stole information and sold it to dark web and earned", "You got paid to DDoS one of your friends enemies due to him losing in 1v1 on cod and got paid", "You steal oil from nearby gas station and sell it to the dark web and earned", "You steal a rare tiger and sell it on the dark web and earned", "You steal someone else's paycheck and got", "You steal from domino's and got", "You steal from Mr.Beast and earned", "You steal from cocomelon and earned", "You steal an old women purse and earned", "You hack Steam's bank account and earned", "You hacked into KFC to steal their recipe and You sold it to the dark web and earned", "You hacked into the Hello Kitty company stealing the data and selling it for",
              "You stole from Elon Musk and earned", "You stole a bike from a biker gang and sold it for", "You stole the Math Exams answers and sold it to your friends for", "You stole Vondy money and earned", "You stole the Mcdonalds secret ketchup sauce and sold it to the dark web and earned", "You stole Disney new cartoon movie and sold it and earned", "You got paid to beat up Elon Musk and earned.", "You stole a old grandma cane and sold it for", "You hacked into Queen Elizabeth bank account and stole", "You tricked Billy Bob into giving You his debit card information and You stole", "You steal a Logitech G502 hero mouse from Walmart and sold it to your buddy for", "You stole clothing from the Royale Family and sold it for", "You breach into Discord Database stealing sensitive information and selling it for", "You stole Monet’s artwork from a museum and earned", "You sold limited edition Among US items on the dark web and earned", "You stole a spaceship to become the first person on Mars and earned", "You steal from a handsome beard man that has his body pierce and earned"]

crime_fail_list = ["You tried to rob a guy but got jumped and mugged and lost", "You tried to steal from Billy Bob cafe but You set off a silent alarm and got arrested and fined for", "You tried to steal from a Karen but she assaulted You with her cane and You had to pay hospital bills which was", "You tried to steal from Billy Bob but his gang members assaulted You and You had to pay hospital bills which was", "You and your fellow gang members went to rob a store but got mugged by rival gang members and lost", "You tried to rob a undercover cop and got fined", "You tried to steal from school but a teacher caught You and You was fined", "You was seen littering on camera and was fined", "You successfully pulled off a bank heist and while escaping You broke your leg and the hospital bill was", "You tried to rob ShadowKing but fail and got mugged and lost",
                   "You try to rob the Nazi but it backfired and You got held hostage and had to pay", "You try to steal from dwayn johnson but it backfired and got mugged for", "You tried to steal a car but got caught by a cop and was fined", "You tried to steal from a grandpa but he mugged You for", "You tried to sneak in walmart to steal but got caught by security guard and got fined", "You tried to steal your neighbor vase but go caught and fined for", "You tried to beat up a college student but it backfired and You got shot and the hospital bill was", "You rob your grandaughter but she beat beat You up and your hospital bill was", "You eat the stolen cheeseburger You found and got fined for", "You try to steal from an old champion boxer house and got beat up and he stole your wallet which contained", "You try to steal the moon but the cops found You and You got fined for"]

daily_paycheck_list = ["You got your daily paycheck for doing nothing and earned", "Your mom gave You your daily allowance and got", "You got your daily paycheck from Twitch and earned", "You got your daily paycheck from Youtube and earned", "You got your daily paycheck for playing Clash of Clans and earned", "You got your daily paycheck from McDonalds and earned", "You got your daily paycheck for being a roblox youtuber and earned", "You earned your daily paycheck for being a clown and earned", "You got your Daily Allowance from your mom and earned",
                       "You take care of a customer house and they give You your paycheck and You earn", "You got your daily paycheck from a discord staff member and earned", "You got your daily paycheck for working for the Stokes Twins and earned", "You got your daily income from stocks You invested in and earned", "After a day of bitcoin mining You earned", "You got your daily earnings for your Real Estate business and earned", "You got your daily earnings for your McDonalds Franchise You own and earned", "You tried to rob a handsome beard man but he overpowered You and robbed You and earned"]


beg_list = ["You begged a homeless man for money and he gave You", "You begged for money from the Converged Outlaws and they gave You", "You and your friends tried to setup a Samurai but broke your ankle and had to pay for your hospital bill which was", "You try to steal from Uncle Roger but it backfired and he stole from You and he earned", "You try to hack into Activison to make wallhacks and was fined for", "You tried to hack into Riot Games but got busted and You was fined for", "You beg Pewdiepie for money and got", "You begged Jeff Bezos for money and he gave You", "You begged for donations from Riot Games and earned", "You beg for a playstation 5 from jacksepticye instead he gave You", "You begged for Bitcoin from Jack The Ripper and he gave You bitcoin which was worth", "You begged your girlfriend for money to the NBA game and she gave You",
            "You begged your boyfriend for money for lipstick and he gave You", "You begged for money from a mysterious mustache man and he kindly gave You", "You beg for money from a undecover secret agent and she gave You", "You beg for money from Shadowking and he gave You", "You beg for money from Mojang and they gave You", "You begged a restaurant owner for money and she gave You", "You begged your mother for money for Domino's Pizza and she gave You", "You begged a priest for money and he gave You", "You begged a school friend for money and he gave You", "You begged harry potter and earned"]


hourly_paycheck_list = ["You got your hourly paycheck for making professional Clash of Clan bases and earned", "You got your hourly paycheck for being a Math tutor and earned", "You cleaned the bathroom at Mcdonalds and earned", "You shoveled up the snow out of the driveway in a pile in the freezing weather and earned",
                        "You got your hourly paycheck for being a manager for a famous Roblox youtuber and earned", "You got your hourly paycheck for being support in the 24/7 Casino discord server and earned", "You got your hourly paycheck for being a Moderator in 24/7 Casino Discord Server and earned", "You got your hourly paycheck for being a developer for the 24/7 Casino Discord bot", "You receive your hourly paycheck from Goated#2235 and earned", "You receive your hourly paycheck from a developer for Youtube and earned", "You receive your hourly paycheck from Gaby and earned", "You receive your hourly paycheck from a very well talented English speaker and earned", "You got your hourly paycheck by playing Counter-Strike: Global Offensive and earned", "You got your hourly paycheck by playing war thunder and earned", "You got your hourly paycheck by playing captain of industry and earned", "You got your hourly paycheck from ShadowKing and earned", "You got your hourly paycheck by adding a suggestion to the 247 casino bot and earned", "You got your hourly paycheck by playing tap ninja and earned", "You got your hourly paycheck for tuning into a livestream and earned", "You got your hourly paycheck at hershey's and earned", "You got your hourly paycheck from your arrogant boss and earned", "You got your hourly paycheck for changing your name and earned"]


beg_failed_list = ["You begged a homeless man for money and he said he didn't have any money so You started begging with him and earned", "You beg from a cow and earned", "You beg Halo for money but he did not have any money and thus didn't give You any and You earned",  "You begged Bill Gates for money but he said he was poor so You earned", "You begged your mom for money for your gambling addiction but she said go get a job and You earned",
                   "You begged Donald Trump for some money and a swigg of his Coke but he declined and You earned", "You begged Vondy for money but he spent his last money on blackjack and lost it all so he's broke and You earned", "You beg a Karen for money and she made a scene and You earned", "You begged for money from handsome beard man but he just spent all his money on alcohol and You earned", "You beg from sketchyly but he play minecraft and You earned", "You beg from from roblox but that game is dead and You earned", "You beg from hokey man but he is playing and You earned", "You beg from a HOLY GOAT but she is broke and You earned", "You beg from a HOLY COW but hes broke and You earned"]


weekly_list = ["You got your weekly paycheck for being a supporter and earned",
               "You got your weekly paycheck for working at mcdonalds and earned."]

monthly_list = ["You got your monthly paycheck for being a developer and earned", "You got your monthly check for being a stay home mother and earned", "You got your monthly check for working at Walmart"]

search_list = ["You searched under your friend couch and found", "You searched around in Krogers trash can and found","You search under the bed in your house and found","You search on top of the bed of your house and found","You search the side of the bed next to the  coffee table and found","You searched the lawn on your house and found","You search your bro's house and found","You search the girl's house and found","You search Mr.incredible speacial suit and found","You search michol angelo hat and found","You search ShadowKing pants and found","You search the discord bar and found","You search Venom speacial house and found","You search clash royale and found","You search War thunder speacial website and found","You search willy wonka factory and found","You search tommy innit and found""You search the roof of your nearby cinema and found","You search the seats at church and found","You search the priests staff and found","You search your apartment and found","You search your bossy office and found","You search RAV endpoint protection terms and service and found","You search ShadowQueen wallet and found","You search under the bed in your house and found","You search on top of the bed of your house and found","You search the side of the bed next to the  coffee table and found","You searched the lawn on your house and found","You search your bro's house and found","You search the girl's house and found","You search pewdiepie and found","You search youtube and found",]

