working_list = ["You helped Elon Musk lay off his employees and earned", "You worked at mcdonalds for 8 hours and earned", "You were fixing roofs and earned", "You started working as a Minecraft Youtuber and earned", "You started working as a discord moderator and earned", "You started working as a python developer and earned", "You fixed a major bug in the 24/7 Casino Bot and earned", "You fought for the UFC and knocked out Mike Tyson and earned", "You worked at pizza hut from 8am to 4pm and earned", "You won a Fortnite tournament and won", "You worked at a gas station for 8 hours and earned", "You serveed in the Soviet union and earned", "You worked as a maid for the Nazis and earned", "You worked at Wendy's overnight and earned", "You mopped the floor in your house and got", "You help your team group project by a lot and earned", "You work for Popeye's and earned", "You worked at the car wash and earned",
                "You worked as a Mechanical Keyboard Maker and earned", "You did your house chores and earned", "You helped your school organization and earned", "You worked as a church janitor and got paid", "You worked for the handsome bearded man and he gave you a tip of", "You worked as a producer in the show Kitchen Nightmares and earned", "You worked as Billy Bob assistant and he gave you a fine tip of", "You worked overnight at Walmart for one hour and earned", "You share your design which goes well and you earned", "You built a spaceship for NASA and earned", "You leaked Hillary Clinton’s email addresses and earned", "You worked in the animal shelter and earned", "You cleaned the garden and earned", "You worked as a janitor and earned", "You worked as Blackpink Producer and earned", "You worked as BTS Producer and earned", "You helped your grandma to cook and earned"]

crime_list = ["You helped FTX in their Bitcoin Ponzi Scheme and Bankman-Fried gave you","You stole from Upgrade.chat bank account and earned", "You stole from Mcdonalds and resold the stolen goods on the black market and earned", "You stole Pablo Esobar's drug stash and sold it for", "You beat up the school bully and got paid", "You hacked into the goverment and stole", "You successfully started a bank heist and stole", "You robbed Bill Gates and stole", "You stole a computer from school, sold it and made", "You hacked into Wikipedia and stole information and sold it to dark web and earned", "You got paid to DDoS one of your friends enemies due to him losing a 1v1 in cod and got paid", "You steal oil from nearby gas station and sell it on the dark web and earned", "You steal a rare tiger and sell it on the dark web and earned", "You steal someone else's paycheck and got", "You steal from domino's and got", "You steal from Mr.Beast and earned", "You steal from cocomelon and earned", "You steal an old women purse and earned", "You hack Steam's bank account and earned", "You hacked into KFC to steal their recipe and You sold it to the dark web and earned", "You hacked into the Hello Kitty company stealing the data and selling it for",
              "You stole from Elon Musk and earned", "You stole a bike from a biker gang and sold it for", "You stole the Math Exams answers and sold it to your friends for", "You stole Vondy's money and earned", "You stole the Mcdonalds secret ketchup sauce and sold it to the dark web and earned", "You stole Disney's new cartoon movie and sold it and earned", "You got paid to beat up Elon Musk and earned.", "You stole an old grandma's cane and sold it for", "You hacked into Queen Elizabeth's bank account and stole", "You tricked Billy Bob into giving You his debit card information and stole", "You steal a Logitech G502 hero mouse from Walmart and sold it to your buddy for", "You stole clothing from the Royal Family and sold it for", "You breached into Discord Database stealing sensitive information and selling it for", "You stole Monet’s artwork from a museum and earned", "You sold limited edition Among US items on the dark web and earned", "You stole a spaceship to become the first person on Mars and earned", "You steal from a handsome beard man that has his body pierce and earned"]

crime_fail_list = ["You tried to ping Goated for money but he declined and u earned","You tried to hack into Billy Bob's laptop but he caught you and u were fined","You tried to rob a guy but got jumped and mugged and lost", "You tried to steal from Billy Bob cafe but you set off a silent alarm and got arrested and fined for", "You tried to steal from a Karen but she assaulted you with her cane and you had to pay hospital bills which cost you", "You tried to steal from Billy Bob but his gang members assaulted you and you had to pay hospital bills which was", "You and your fellow gang members went to rob a store but got mugged by rival gang members and lost", "You tried to rob a undercover cop and got fined", "You tried to steal from school but a teacher caught you and you was fined", "You were seen littering on camera and was fined", "You successfully pulled off a bank heist and while escaping you broke your leg and the hospital bill was", "You tried to rob ShadowKing but fail and got mugged and lost",
                   "You try to rob the Nazi but it backfired and You got held hostage and had to pay", "You try to steal from Dwain Johnson but it backfired and you got mugged for", "You tried to steal from Uncle Roger but it backfired and he stole", "You tried to hack into Activison to make wallhacks and was fined for", "You tried to hack into Riot Games but got busted and you were fined for","You tried to steal a car but got caught by a cop and was fined", "You tried to steal from a grandpa but he mugged you and you lost", "You tried to sneak into walmart to steal but got caught by security guard and got fined", "You tried to steal your neighbor's vase but got caught and fined for", "You tried to beat up a college student but it backfired and You got shot and the hospital bill was", "You robbed your grandaughter but she beat you up and your hospital bill was", "You ate the stolen cheeseburger you found and got fined for", "You tried to steal from an old champion boxer's house and got beat up and he stole your wallet which contained", "You tried to steal the moon but the cops found you and you got fined for"]

daily_paycheck_list = ["You streamed on Twitch for a day and some kind people donated a total of ","You got your daily paycheck for doing nothing and earned", "Your mom gave you your daily allowance and got", "You got your daily paycheck from Twitch and earned", "You got your daily paycheck from Youtube and earned", "You got your daily paycheck for playing Clash of Clans and earned", "You got your daily paycheck from McDonalds and earned", "You got your daily paycheck for being a roblox youtuber and earned", "You earned your daily paycheck for being a clown and earned", "You got your Daily Allowance from your mom and earned",
                       "You take care of a customer house and they give you your paycheck and you earned", "You got your daily paycheck from a discord staff member and earned", "You got your daily paycheck for working for the Stokes Twins and earned", "You got your daily income from stocks You invested in and earned", "After a day of bitcoin mining you earned", "You got your daily earnings for your Real Estate business and earned", "You got your daily earnings for your McDonalds Franchise you own and earned", "You tried to rob a handsome beard man but he overpowered you and robbed you and earned"]


beg_list = ["You tried begging Elon Musk but he's in debt from buying Twitter and you earned","You tried begging Andrew Tate for money but he declined and u earned","You begged a homeless man for money and he gave you", "You begged for money from the Converged Outlaws and they gave you", "You beg Pewdiepie for money and got", "You begged Jeff Bezos for money and he gave you", "You begged for donations from Riot Games and earned", "You beg for a playstation 5 from jacksepticeye instead he gave you", "You begged for Bitcoin from Jack The Ripper and he gave you bitcoin which was worth", "You begged your girlfriend for money to the NBA game and she gave you",
            "You begged your boyfriend for money for lipstick and he gave you", "You begged for money from a mysterious mustache man and he kindly gave you", "You beg for money from a undercover secret agent and she gave you", "You beg for money from Shadowking and he gave you", "You beg for money from Mojang and they gave you", "You begged a restaurant owner for money and she gave you", "You begged your mother for money for Domino's Pizza and she gave you", "You begged a priest for money and he gave you", "You begged a school friend for money and he gave you", "You begged harry potter and earned"]


hourly_paycheck_list = ["You got your hourly paycheck for designing discord servers and earned","You got your hourly paycheck for making professional Clash of Clan bases and earned", "You got your hourly paycheck for being a Math tutor and earned", "You cleaned the bathroom at Mcdonalds and earned", "You shoveled up the snow out of the driveway in a pile in the freezing weather and earned",
                        "You got your hourly paycheck for being a manager for a famous Roblox youtuber and earned", "You got your hourly paycheck for being support in the 24/7 Casino discord server and earned", "You got your hourly paycheck for being a Moderator in 24/7 Casino Discord Server and earned", "You got your hourly paycheck for being a developer for the 24/7 Casino Discord bot", "You receive your hourly paycheck from Goated#2235 and earned", "You receive your hourly paycheck from a developer for Youtube and earned", "You receive your hourly paycheck from Gaby and earned", "You receive your hourly paycheck from a very well talented English speaker and earned", "You got your hourly paycheck by playing Counter-Strike: Global Offensive and earned", "You got your hourly paycheck by playing war thunder and earned", "You got your hourly paycheck by playing captain of industry and earned", "You got your hourly paycheck from ShadowKing and earned", "You got your hourly paycheck by adding a suggestion to the 247 casino bot and earned", "You got your hourly paycheck by playing tap ninja and earned", "You got your hourly paycheck for tuning into a livestream and earned", "You got your hourly paycheck at hershey's and earned", "You got your hourly paycheck from your arrogant boss and earned", "You got your hourly paycheck for changing your name and earned"]


beg_failed_list = ["You begged TommyInnit for coins but all he said was 'Subscribe to my channel' and you earned","IShowSpeed noticed you begging at the Theme Park but he's stingy and you earned", "You begged a gambling addict who just lost his life savings so hes poor and you earned", "You begged Singh for money but he just lost his money in the casino and you earned", "You begged a homeless man for money and he said he didn't have any money so you started begging with him and earned", "You begged from a cow and earned", "You beg Halo for money but he did not have any money and thus didn't give you any and you earned",  "You begged Bill Gates for money but he said he was poor so you earned", "You begged your mom for money for your gambling addiction but she said go get a job and you earned",
                   "You begged Donald Trump for some money and a swigg of his Coke but he declined and you earned", "You begged Vondy for money but he spent his last money on blackjack and lost it all so he's broke and you earned", "You beg a Karen for money and she made a scene and You earned", "You begged for money from handsome beard man but he just spent all his money on alcohol and you earned", "You begged from sketchyly but he play minecraft and you earned", "You beg from from roblox but that game is dead and you earned", "You beg from hokey man but he is playing and you earned", "You beg from a HOLY GOAT but she is broke and you earned", "You beg from a HOLY COW but hes broke and you earned"]


weekly_list = ["You got your weekly paycheck from washing your neighbor's cars for a week and earned","You got your weekly paycheck for being a supporter and earned",
               "You got your weekly paycheck for working at mcdonalds and earned", "You got your weekly paycheck for helping Elon Musk lay off his employees and earned"]

monthly_list = ["You got your monthly paycheck from your Roblox game revenue and earned","You got your monthly paycheck for selling sweets to children and earned","You got your monthly paycheck for being a developer and earned", "You got your monthly check for being a stay home mother and earned", "You got your monthly check for working at Walmart"]


search_list = ["You searched in the Egyptian Pyramids and found","You searched for coins in the casino and found","You searched 24/7 Casino's code and somehow found", "You searched Twitter headquarters and found", "You searched under your friend couch and found", "You searched around in Krogers trash can and found","You search under the bed in your house and found","You search on top of the bed of your house and found","You search the side of the bed next to the  coffee table and found","You searched the lawn on your house and found","You search your bro's house and found","You search the girl's house and found","You search Mr.incredible speacial suit and found","You search michol angelo hat and found","You search ShadowKing pants and found","You search the discord bar and found","You search Venom speacial house and found","You search clash royale and found","You search War thunder speacial website and found","You search willy wonka factory and found","You search tommy innit and found""You search the roof of your nearby cinema and found","You search the seats at church and found","You search the priests staff and found","You search your apartment and found","You search your bossy office and found","You search RAV endpoint protection terms and service and found","You search ShadowQueen wallet and found","You search under the bed in your house and found","You search on top of the bed of your house and found","You search the side of the bed next to the  coffee table and found","You searched the lawn on your house and found","You search your bro's house and found","You search the girl's house and found","You search pewdiepie and found","You search youtube and found"]

search_list = ["You searched under your friend couch and found", "You searched around in Krogers trash can and found","You search under the bed in your house and found","You search on top of the bed of your house and found","You search the side of the bed next to the  coffee table and found","You searched the lawn on your house and found","You search your bro's house and found","You search the girl's house and found","You search Mr.incredible speacial suit and found","You search michol angelo hat and found","You search ShadowKing pants and found","You search the discord bar and found","You search Venom speacial house and found","You search clash royale and found","You search War thunder speacial website and found","You search willy wonka factory and found","You search tommy innit and found""You search the roof of your nearby cinema and found","You search the seats at church and found","You search the priests staff and found","You search your apartment and found","You search your bossy office and found","You search RAV endpoint protection terms and service and found","You search ShadowQueen wallet and found","You search under the bed in your house and found","You search on top of the bed of your house and found","You search the side of the bed next to the  coffee table and found","You searched the lawn on your house and found","You search your bro's house and found","You search the girl's house and found","You search pewdiepie and found","You search youtube and found"]

volunteer = ["You volunteer to clean up the neighborhood and earned","You volunteer at a local soup kitchen and earned","You organize a charity event and earned","You tutor students after school and earned","You participate in a beach cleanup and earned","You help organize a community garden and earned","You assist elderly residents with their daily tasks and earned","You volunteer at a homeless shelter and earned","You join a youth mentoring program and earned","You donate blood at a community blood drive and earned","You participate in a Habitat for Humanity build and earned","You teach computer skills to underprivileged children and earned","You volunteer at an animal shelter and earned","You help organize a fundraising walk or run and earned","You serve meals to the homeless at a local shelter and earned","You assist in disaster relief efforts and earned","You volunteer at a local library and earned","You help clean up a park and earned","You spend time with the elderly at a nursing home and earned","You assist in organizing a community recycling program and earned","You coach a youth sports team and earned"]
